package config

// orgDefinitions lists all 18 advisory organisations (15 local + 3 Murican).
// Murican orgs are not shown in the Evidence tab by default; they surface only
// through TICKY_PRESSURE events. See game_design.md Evidence section for full rationale.
var orgDefinitions = []OrgDefinition{

	// ------------------------------------------------------------------
	// LOCAL CONSULTANCIES
	// ------------------------------------------------------------------

	{
		ID:      "tacute_energy",
		Name:    "Tacute Energy Solutions",
		OrgType: OrgConsultancy,
		Origin:  OrgLocal,
		BaseCost: 280.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 4, Max: 7},
		Quality:                QualityRange{Min: 70, Max: 95},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.25,
		PopularityRisk:         0.20,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightPower, InsightIndustry, InsightEnergyMarket},
	},
	{
		ID:      "meridian_strategy",
		Name:    "Meridian Strategy",
		OrgType: OrgConsultancy,
		Origin:  OrgLocal,
		BaseCost: 220.0,
		DeliveryDist:           TriangularDist{Min: 2, Mode: 3, Max: 8},
		Quality:                QualityRange{Min: 30, Max: 85},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.40,
		PopularityRisk:         0.40,
		BaseFailureProbability: 0.09,
		Specialisms: []InsightType{InsightPolicy, InsightEconomy, InsightClimate},
	},
	{
		ID:      "clearpath_advisory",
		Name:    "ClearPath Advisory",
		OrgType: OrgConsultancy,
		Origin:  OrgLocal,
		BaseCost: 240.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 9},
		Quality:                QualityRange{Min: 40, Max: 85},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.40,
		PopularityRisk:         0.40,
		BaseFailureProbability: 0.08,
		Specialisms: []InsightType{InsightBuildings, InsightIndustry, InsightRetrofit},
	},
	{
		ID:      "vertex_policy",
		Name:    "Vertex Policy Group",
		OrgType: OrgConsultancy,
		Origin:  OrgLocal,
		BaseCost: 150.0,
		DeliveryDist:           TriangularDist{Min: 1, Mode: 2, Max: 6},
		Quality:                QualityRange{Min: 25, Max: 80},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.45,
		PopularityRisk:         0.40,
		BaseFailureProbability: 0.14,
		Specialisms: []InsightType{InsightPolicy, InsightTransport},
	},
	{
		ID:      "axiom_infrastructure",
		Name:    "Axiom Infrastructure",
		OrgType: OrgConsultancy,
		Origin:  OrgLocal,
		BaseCost: 260.0,
		DeliveryDist:           TriangularDist{Min: 4, Mode: 6, Max: 10},
		Quality:                QualityRange{Min: 50, Max: 90},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.35,
		PopularityRisk:         0.35,
		BaseFailureProbability: 0.06,
		Specialisms: []InsightType{InsightBuildings, InsightRetrofit, InsightIndustry},
	},

	// ------------------------------------------------------------------
	// LOCAL THINK TANKS
	// ------------------------------------------------------------------

	{
		ID:      "albion_institute",
		Name:    "The Albion Institute",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 80.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 40, Max: 70},
		BiasType:               BiasIdeological,
		BiasDirection:          0.60, // right-leaning, free market
		PopularityRisk:         0.50,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightEconomy, InsightPolicy},
	},
	{
		ID:      "common_wealth_foundation",
		Name:    "Common Wealth Foundation",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 70.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 40, Max: 72},
		BiasType:               BiasIdeological,
		BiasDirection:          -0.60, // left-leaning, public ownership
		PopularityRisk:         0.45,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightEconomy, InsightIndustry},
	},
	{
		ID:      "progress_policy_centre",
		Name:    "Progress Policy Centre",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 75.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 45, Max: 75},
		BiasType:               BiasIdeological,
		BiasDirection:          -0.20, // centre-left, credible
		PopularityRisk:         0.25,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightPolicy, InsightEconomy, InsightClimate},
	},
	{
		ID:      "green_futures_forum",
		Name:    "Green Futures Forum",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 65.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 40, Max: 70},
		BiasType:               BiasIdeological,
		BiasDirection:          -0.30, // pro-environment
		PopularityRisk:         0.30,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightClimate, InsightPower, InsightBuildings},
	},
	{
		ID:      "energy_realists_network",
		Name:    "Energy Realists Network",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 60.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 30, Max: 65},
		BiasType:               BiasIdeological,
		BiasDirection:          0.70, // fossil-fuel sympathetic
		PopularityRisk:         0.70,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightEnergyMarket, InsightPower},
	},
	{
		ID:      "heritage_uk",
		Name:    "Heritage UK",
		OrgType: OrgThinkTank,
		Origin:  OrgLocal,
		BaseCost: 65.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 10},
		Quality:                QualityRange{Min: 35, Max: 68},
		BiasType:               BiasIdeological,
		BiasDirection:          0.50, // centre-right, FarRight adjacent
		PopularityRisk:         0.55,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightPolicy, InsightEconomy},
	},

	// ------------------------------------------------------------------
	// LOCAL ACADEMIC
	// ------------------------------------------------------------------

	{
		ID:      "northern_climate_research",
		Name:    "Northern Climate Research Centre",
		OrgType: OrgAcademic,
		Origin:  OrgLocal,
		BaseCost: 90.0,
		DeliveryDist:           TriangularDist{Min: 6, Mode: 9, Max: 18},
		Quality:                QualityRange{Min: 65, Max: 95},
		BiasType:               BiasNone,
		PopularityRisk:         0.05,
		BaseFailureProbability: 0.03,
		Specialisms: []InsightType{InsightClimate, InsightEnergyMarket},
	},
	{
		ID:      "institute_energy_transition",
		Name:    "Institute for Energy Transition Studies",
		OrgType: OrgAcademic,
		Origin:  OrgLocal,
		BaseCost: 85.0,
		DeliveryDist:           TriangularDist{Min: 6, Mode: 9, Max: 18},
		Quality:                QualityRange{Min: 65, Max: 93},
		BiasType:               BiasNone,
		PopularityRisk:         0.05,
		BaseFailureProbability: 0.03,
		Specialisms: []InsightType{InsightPower, InsightIndustry, InsightClimate},
	},
	{
		ID:      "centre_housing_retrofit",
		Name:    "Centre for Housing and Retrofit",
		OrgType: OrgAcademic,
		Origin:  OrgLocal,
		BaseCost: 80.0,
		DeliveryDist:           TriangularDist{Min: 6, Mode: 9, Max: 18},
		Quality:                QualityRange{Min: 62, Max: 92},
		BiasType:               BiasNone,
		PopularityRisk:         0.05,
		BaseFailureProbability: 0.03,
		Specialisms: []InsightType{InsightBuildings, InsightRetrofit, InsightFuelPoverty},
	},
	{
		ID:      "transport_futures_lab",
		Name:    "Transport Futures Lab",
		OrgType: OrgAcademic,
		Origin:  OrgLocal,
		BaseCost: 80.0,
		DeliveryDist:           TriangularDist{Min: 6, Mode: 9, Max: 18},
		Quality:                QualityRange{Min: 60, Max: 90},
		BiasType:               BiasNone,
		PopularityRisk:         0.05,
		BaseFailureProbability: 0.03,
		Specialisms: []InsightType{InsightTransport},
	},

	// ------------------------------------------------------------------
	// MURICAN ORGS (surfaced only via TICKY_PRESSURE events)
	// ------------------------------------------------------------------

	{
		ID:      "frontier_energy_institute",
		Name:    "Frontier Energy Institute",
		OrgType: OrgThinkTank,
		Origin:  OrgMurican,
		BaseCost: 120.0,
		DeliveryDist:           TriangularDist{Min: 2, Mode: 4, Max: 8},
		Quality:                QualityRange{Min: 30, Max: 65},
		BiasType:               BiasIdeological,
		BiasDirection:          0.85, // strongly anti-net-zero
		PopularityRisk:         0.75,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightEnergyMarket, InsightPower},
	},
	{
		ID:      "american_growth_alliance",
		Name:    "American Growth Alliance",
		OrgType: OrgThinkTank,
		Origin:  OrgMurican,
		BaseCost: 110.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 9},
		Quality:                QualityRange{Min: 35, Max: 70},
		BiasType:               BiasIdeological,
		BiasDirection:          0.65, // anti-regulation economics
		PopularityRisk:         0.65,
		BaseFailureProbability: 0.04,
		Specialisms: []InsightType{InsightEconomy, InsightPolicy},
	},
	{
		ID:      "pinnacle_energy_partners",
		Name:    "Pinnacle Energy Partners",
		OrgType: OrgConsultancy,
		Origin:  OrgMurican,
		BaseCost: 300.0,
		DeliveryDist:           TriangularDist{Min: 3, Mode: 5, Max: 9},
		Quality:                QualityRange{Min: 40, Max: 80},
		BiasType:               BiasClientConfirmation,
		ClientBiasWeight:       0.55, // high -- will tell you what you want to hear
		PopularityRisk:         0.60,
		BaseFailureProbability: 0.07,
		Specialisms: []InsightType{InsightPower, InsightEnergyMarket},
	},
}
